version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/

jobs:
  test:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: node --version
