version: 2.1

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

workflows:
  test:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: node --version
