version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/

jobs:
  test:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: node --version
