name: APPLEBOY

on: workflow_dispatch

jobs:
  Display:
    runs-on: ubuntu-latest
    
    steps:
      - name: Display Message
        run: |
          echo "Hello, World!"
          ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa 
          ssh-copy-id root@${{ secrets.SSH_HOST }}

#       - name: executing remote ssh commands using password
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           script: ls && whoami
