name: APPLEBOY

on: workflow_dispatch

jobs:
    
  Display:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' , 'self-hosted' ]
    steps:
      - name: Display Message
        run: |
          echo "Hello, World!"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: ls && whoami
