name: Build bison wheel on IBMZ

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2  
      - uses: uraimo/run-on-arch-action@v2.2.0
        name: Install dependencies and build grpc
        id: build
        with:
          arch: s390x
          distro: ubuntu20.04
          
          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"
          
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
            
      
          run: |   
            apt-get update -y
            apt-get install -y build-essential autoconf libtool pkg-config git software-properties-common curl 
            add-apt-repository ppa:deadsnakes/ppa -y
            apt-get install python3.9 python3-pip python3-dev libpython3.9-dev -y
            
            #Building bison
            echo "Building grpc ${{ inputs.release }}"
            python3.9 -m pip install --upgrade pip
            python3.9 -m pip install -U wheel setuptools
            python3.9 -m pip install bison==${{ inputs.release }}
            pip download bison -d wheels
            
            WHEEL_PATH=$(find /root/.cache/pip/wheels/ -name "bison-*.whl")
            WHEEL_NAME=$(basename $(find /root/.cache/pip/wheels/ -name "bison-*.whl"))
            echo $WHEEL_PATH
            echo $WHEEL_NAME
            cp $WHEEL_PATH /artifacts/$WHEEL_NAME
            ls /artifacts/
            
            
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.release }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: ./artifacts/bison-${{ inputs.release }}-py2.py3-none-any.whl
          name: ${{ inputs.release }}
          replacesArtifacts: true
          draft: false
          prerelease: false
