name: circleci

on: workflow_dispatch

jobs:
  Display:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
