name: circleci

on: workflow_dispatch

jobs:
  Display:
    runs-on: ubuntu-latest
    
    steps:
      - name: Circle CI
        id: trigger_circle_ci
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
