name: circleci

on: workflow_dispatch

jobs:
  Display:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger CircleCI Pipeline
        uses: circleci/trigger-circleci-pipeline@v1.0
        with:
          project: nothing
          branch: ${{ github.ref }}
          token: ${{ secrets.CCI_TOKEN }}
