name: demo_qemu_buildx

on: workflow_dispatch

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: test docker availablity
        run: |
          docker --version
          docker info

      - name: Enabling Experimental Features
        run: | 
          export DOCKER_CLI_EXPERIMENTAL=enabled

      - name: Supported arhitectures by Docker to build 
        run: |
          docker buildx ls

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Now Supported architectures by Docker to build
        run: |
          docker buildx ls
