name: Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            version: [1.18, 1.19, 1.20, 1.20-test]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
      
      - name: Docker image exists
        uses: cloudposse/github-action-docker-image-exists@0.1.1
        with:
          registry: quay.io
          organization: projectquay
          repository: golang
          tag: ${{ matrix.versions }}
