name: simple workflow example

on: workflow_dispatch

jobs:
  Display:
    runs-on: self-hosted
    
    steps:
      - name: Display Message
        run: |
          echo "Hello, World!"

      - name: Display working directory
        run: |
          pwd
          ls -lart

      - name: Checkout
        uses: actions/checkout@v3

      - name: Display new working directory
        run: |
          pwd
          ls -lart
          top
      
