name: simple workflow example

on: workflow_dispatch

jobs:
  Display:
    runs-on: self-hosted
    
    steps:
      - name: Display Message
        run: |
          echo "Hello, World!"

      - name: ssh
        env:
          USER: ${{ secrets.SSH_USER }}
          HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh $USER@$HOST
          pwd
          ls -lart

      - name: Checkout
        uses: actions/checkout@v3

      - name: Display new working directory
        run: |
          pwd
          ls -lart
