name: simple workflow example

on:
  push:
    branches:
      - main

jobs:
  Display:
    runs-on: ubuntu-latest
    
    steps:
      - name: Display Message
        run: |
          echo "Hello, World!"

      - name: Display working directory
        run: |
          pwd
          ls -lart

      - name: Checkout
        uses: actions/checkout@v3

      - name: Display new working directory
        run: |
          pwd
          ls -lart
