name: Test SSH

on: [push]

jobs:
    
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: start
        env:
          KEY: ${{ secrets.SATYAM_KEY }}
        run: |
          whoami;
          ls-la
          echo "$KEY" > secret
          chmod 600 secret
          ls -la
          cat secret
          ssh -V
          ssh -i secret root@141.125.111.100
          ls -la
