name: Test SSH

on: workflow_dispatch

jobs:
    
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: start
        env:
          KEY: ${{ secrets.SATYAM_KEY }}
        run: |
          whoami;
          ls
          echo "$KEY" > secret
          chmod 600 secret
          ls
          cat secret
          ssh -V
